### ISSUE TITLE
Writing less code

### ISSUE THREAD

**Issue by alisamadiii** [RakeshSangem/Sharkfolio#35]
Instead of writing this much code which are all same, You can make an array and store the data and use map method.
What you think?
![image](https://user-images.githubusercontent.com/99729607/193489277-7d53c012-d2da-43ea-a89d-d51e02588660.png)

**Comment by alisamadiii** [comment]
Or You can make a component.

**Comment by zelfroster** [comment]
Yes Yes... We initially were going to do the same.. But our members didn't knew much about React workflow they learnt on the go and did it in the last moments..
We actually thought of using any API for that but couldn't find one... If you do find one we can use it...
For now.. I am assigning it to you.. and you can work on it :)

**Comment by alisamadiii** [comment]
I am not going to use any API but I'll make two components and make the codes to look clean and easy to read for readers.

**Comment by RakeshSangem** [comment]
Hey @AliReza1083, I agree what you have mentioned.

Thanks for the support 💙
