### ISSUE TITLE
[DOCS] improve documentation of Sharkfolio

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/Sharkfolio#39]
The current documentation is not user friendly.

It does not provide enough information about the project.

We need to make sure that our users have the information they need in order to use our project correctly.

- Improve the flow of documentation
- Add license, contributing etc. info.

**Comment by stevenjburrows** [comment]
I can add the contributing.md if you want

**Comment by RakeshSangem** [comment]
> I can add the contributing.md if you want

Assigned👍
